apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: pod2-nw2
spec:
  config: >
    {
        "cniVersion": "0.3.1",
        "name": "pod2-nw2",
        "plugins": [{
            "type": "macvlan",
            "master": "ens224",
            "mode": "bridge",
            "ipMasq": true,
            "ipam": {
              "type": "static",
                "addresses": [
                  {
                    "address": "192.168.10.211/24"
                  }
                ]
            }
        }]
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2-nw2
  annotations:
    k8s.v1.cni.cncf.io/networks: pod2-nw2
spec:
  containers:
  - name: pod2-nw2
    image: wbitt/network-multitool
