apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: centos
  name: centos
spec:
  dataVolumeTemplates:
  - metadata:
      name: centos-dv
      annotations:
        kubevirt.io/provisionOnNode: kubevirt-control-plane
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: hostpath-storage
      source:
        registry:
          url: "docker://quay.io/containerdisks/centos:8.4"
          pullMethod: node # [(Not node name) node pullMode uses host cache for container images]
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: centos
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: dv
          - disk:
              bus: virtio
            name: cloudinitdisk
        resources:
          requests:
            memory: 2G
            cpu: "2000m"
          interfaces:
          - name: default
            bridge: {}            
      networks:
      - name: default
        pod: {}            
      volumes:
      - dataVolume:
          name: centos-dv
        name: dv
      - cloudInitNoCloud:
          networkData: |
            version: 2
            ethernets:
              eth0:
                dhcp4: true
              eth1:
                dhcp4: true
          userData: |
            #cloud-config
            hostname: centos
            user: root
            password: passwd
            chpasswd: { expire: False }
            ssh_pwauth: True
            disable_root: false
            ssh_authorized_keys:
            - ssh-rsa PUBLIC_SSH_KEY
            runcmd:
              - cd /etc/yum.repos.d/
              - sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
              - sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* 
              - yum install wget -y
        name: cloudinitdisk
