apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win2k19
spec:
  dataVolumeTemplates:
  - metadata:
      name: win2k19
      annotations:
        kubevirt.io/provisionOnNode: node
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: hostpath-storage
      source:
        http:
          url: "https://software-download.microsoft.com/download/pr/17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso"
  - metadata:
      name: winhd
      annotations:
        kubevirt.io/provisionOnNode: node
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: hostpath-storage
      source:
        blank: {}
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: win2k19
    spec:
      domain:
        devices:
          disks:
          - bootOrder: 1
            cdrom:
              bus: sata
            name: cdromiso
          - disk:
              bus: virtio
            name: harddrive
          - cdrom:
              bus: sata
            name: virtiocontainerdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 8G
            cpu: "2000m"            
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: win2k19
      - name: harddrive
        persistentVolumeClaim:
          claimName: winhd
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: virtiocontainerdisk
---
apiVersion: v1
kind: Service
metadata:
  name: windows
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: rdp
    nodePort: 30389
    port: 27020
    protocol: TCP
    targetPort: 3389
  selector:
    kubevirt.io/domain: win2k19
  type: NodePort
